// Why: Pi delegates through the `subagent` extension, which dispatches ASYNC jobs and
// emits lifecycle events carrying only a job id. The role and task text live in the
// `subagent` tool call, the job id only in its result, and the terminal outcome in the
// job record on disk. This joins the three inside the status extension so a Pi pane
// publishes the same `subagents` list Claude and Codex publish — no change to the
// subagent extension itself.
/** Subscribes the extension to Pi's child lifecycle events. The subscription and the
 *  roster it feeds live on the event bus, so an extension reload reuses both instead
 *  of double-subscribing or losing the jobs that are still running. */
export function getPiAgentStatusSubagentLifecycleSubscriptionSourceLines(): string[] {
  return [
    '  const piEventBus = (pi as { events?: { on?: (name: string, handler: (event: unknown) => void) => void } }).events',
    '  const lifecycleState = (piEventBus as { __orcaPiSubagents?: { active: Set<string>; waiting: boolean; jobs?: Map<string, OrcaSubagentJob>; onEvent?: (event: unknown, forcedStatus?: string) => void; listener?: (event: unknown) => void } } | undefined)?.__orcaPiSubagents ?? { active: new Set<string>(), waiting: false }',
    '  if (piEventBus) (piEventBus as { __orcaPiSubagents?: unknown }).__orcaPiSubagents = lifecycleState',
    '  if (!lifecycleState.jobs) lifecycleState.jobs = new Map<string, OrcaSubagentJob>()',
    '  adoptSubagentJobs(lifecycleState.jobs)',
    '  if (piEventBus?.on && !(lifecycleState as { listener?: unknown }).listener) {',
    '    const listener = (event: unknown) => lifecycleState.onEvent?.(event)',
    '    lifecycleState.listener = listener',
    "    piEventBus.on('task:subagent:lifecycle', listener)",
    "    piEventBus.on('subagent:async-started', (event: unknown) => lifecycleState.onEvent?.(event, 'started'))",
    "    piEventBus.on('subagent:async-complete', (event: unknown) => lifecycleState.onEvent?.(event, 'completed'))",
    '  }'
  ]
}

export function getPiAgentStatusSubagentRosterSourceLines(): string[] {
  return [
    'type OrcaSubagentTask = { agentType?: string; description?: string }',
    'type OrcaSubagentJob = { tasks: OrcaSubagentTask[]; startedAt: number }',
    '// Pi caps active jobs at 4; the slack absorbs a control call racing a launch.',
    'const SUBAGENT_JOB_MAX = 8',
    'const SUBAGENT_DESCRIPTION_MAX = 120',
    'const SUBAGENT_SWEEP_INTERVAL_MS = 1500',
    'let subagentJobs: Map<string, OrcaSubagentJob> = new Map()',
    'let pendingSubagentLaunches: { toolCallId: string; tasks: OrcaSubagentTask[] }[] = []',
    'let lastSubagentSweepAt = 0',
    '',
    '// The live map is owned by the event bus so an extension reload keeps the roster.',
    'function adoptSubagentJobs(jobs: Map<string, OrcaSubagentJob>): void {',
    '  subagentJobs = jobs',
    '}',
    '',
    'function clearSubagentJobs(): void {',
    '  subagentJobs.clear()',
    '  pendingSubagentLaunches = []',
    '}',
    '',
    '// One short line next to the role, like the parent row shows its prompt.',
    'function subagentTaskBrief(value: unknown): string | undefined {',
    "  if (typeof value !== 'string') return undefined",
    '  for (const line of value.split(/\\r?\\n/)) {',
    '    const trimmed = line.trim()',
    '    if (!trimmed) continue',
    '    return trimmed.length > SUBAGENT_DESCRIPTION_MAX',
    "      ? trimmed.slice(0, SUBAGENT_DESCRIPTION_MAX - 1) + '…'",
    '      : trimmed',
    '  }',
    '  return undefined',
    '}',
    '',
    'function readSubagentLaunchTasks(input: unknown): OrcaSubagentTask[] {',
    "  if (!input || typeof input !== 'object') return []",
    '  const args = input as Record<string, unknown>',
    "  if (args.action !== undefined && args.action !== 'launch') return []",
    '  // A chain runs its steps one at a time, so it is one live child, not one per step.',
    '  const specs =',
    '    Array.isArray(args.tasks) && args.tasks.length > 0',
    '      ? args.tasks',
    '      : Array.isArray(args.chain) && args.chain.length > 0',
    '        ? args.chain.slice(0, 1)',
    "        : typeof args.agent === 'string'",
    '          ? [{ agent: args.agent, task: args.task }]',
    '          : []',
    '  const tasks: OrcaSubagentTask[] = []',
    '  for (const spec of specs) {',
    "    const item = (spec && typeof spec === 'object' ? spec : {}) as Record<string, unknown>",
    "    const agentType = typeof item.agent === 'string' ? item.agent.trim() : ''",
    '    const description = subagentTaskBrief(item.task)',
    '    tasks.push({',
    '      ...(agentType ? { agentType } : {}),',
    '      ...(description ? { description } : {})',
    '    })',
    '  }',
    '  return tasks',
    '}',
    '',
    'function trackSubagentLaunch(event: unknown): void {',
    '  const call = (event ?? {}) as { toolName?: unknown; toolCallId?: unknown; input?: unknown }',
    "  if (call.toolName !== 'subagent') return",
    '  const tasks = readSubagentLaunchTasks(call.input)',
    '  if (tasks.length === 0) return',
    "  const toolCallId = typeof call.toolCallId === 'string' ? call.toolCallId : ''",
    '  pendingSubagentLaunches.push({ toolCallId, tasks })',
    '  if (pendingSubagentLaunches.length > SUBAGENT_JOB_MAX) pendingSubagentLaunches.shift()',
    '}',
    '',
    '// The lifecycle event fires inside execute(), before the result exposes the job id,',
    '// so it can only claim a launch that is unambiguous; the result then binds by id.',
    'function takeSubagentLaunch(toolCallId: string | undefined): OrcaSubagentTask[] | undefined {',
    '  if (pendingSubagentLaunches.length === 0) return undefined',
    '  const index = toolCallId',
    '    ? pendingSubagentLaunches.findIndex((entry) => entry.toolCallId === toolCallId)',
    '    : pendingSubagentLaunches.length === 1',
    '      ? 0',
    '      : -1',
    '  if (index < 0) return undefined',
    '  return pendingSubagentLaunches.splice(index, 1)[0].tasks',
    '}',
    '',
    'function startSubagentJob(jobId: string, tasks?: OrcaSubagentTask[]): boolean {',
    '  if (!jobId) return false',
    '  const existing = subagentJobs.get(jobId)',
    '  if (existing) {',
    '    if (!tasks || tasks.length === 0 || existing.tasks.length > 0) return false',
    '    existing.tasks = tasks',
    '    return true',
    '  }',
    '  if (subagentJobs.size >= SUBAGENT_JOB_MAX) return false',
    '  subagentJobs.set(jobId, { tasks: tasks ?? [], startedAt: Date.now() })',
    '  return true',
    '}',
    '',
    'function dropSubagentJob(jobId: string): boolean {',
    '  return subagentJobs.delete(jobId)',
    '}',
    '',
    '// The tool result is the only place the dispatched job id is exposed.',
    'function observeSubagentToolResult(event: unknown): boolean {',
    '  const end = (event ?? {}) as { toolName?: unknown; toolCallId?: unknown; result?: unknown }',
    "  if (end.toolName !== 'subagent') return false",
    "  const toolCallId = typeof end.toolCallId === 'string' ? end.toolCallId : undefined",
    '  const launched = takeSubagentLaunch(toolCallId)',
    '  const job = (end.result as { details?: { job?: Record<string, unknown> } } | null)?.details',
    '    ?.job',
    "  if (!job || typeof job.jobId !== 'string' || !job.jobId) return false",
    "  if (job.status !== 'running') return dropSubagentJob(job.jobId)",
    '  const agents = Array.isArray(job.agents) ? job.agents : []',
    "  const named = agents.map((agent) => (typeof agent === 'string' ? { agentType: agent } : {}))",
    '  return startSubagentJob(job.jobId, launched ?? named)',
    '}',
    '',
    'function subagentJobsDir(): string {',
    '  const agentDir = process.env.PI_CODING_AGENT_DIR',
    "  if (agentDir) return agentDir + '/subagent-jobs'",
    '  const home = process.env.HOME || process.env.USERPROFILE',
    "  return home ? home + '/.pi/agent/subagent-jobs' : ''",
    '}',
    '',
    '// The record is the authority for a finished job: the subagent extension settles its',
    '// lifecycle only once the result has been handed to the agent, which can be a whole',
    '// turn later. An unreadable record proves nothing, so it settles nothing.',
    'function sweepSettledSubagentJobs(sessionId: unknown): void {',
    "  if (subagentJobs.size === 0 || typeof sessionId !== 'string' || !sessionId) return",
    '  const now = Date.now()',
    '  if (now - lastSubagentSweepAt < SUBAGENT_SWEEP_INTERVAL_MS) return',
    '  lastSubagentSweepAt = now',
    '  const dir = subagentJobsDir()',
    '  if (!dir) return',
    '  for (const jobId of [...subagentJobs.keys()]) {',
    '    try {',
    "      const fs = require('fs')",
    "      const path = dir + '/' + sessionId + '/' + jobId + '.json'",
    "      const record = JSON.parse(fs.readFileSync(path, 'utf8')) as { status?: unknown }",
    "      if (typeof record.status === 'string' && record.status !== 'running') {",
    '        subagentJobs.delete(jobId)',
    '      }',
    '    } catch {',
    '      // Why: the lifecycle event remains the backstop for a record we cannot read.',
    '    }',
    '  }',
    '}',
    '',
    '// Same snapshot shape Claude and Codex publish, so the sidebar builds identical rows.',
    'function subagentStatusSnapshots(sessionId: unknown): Record<string, unknown>[] {',
    '  sweepSettledSubagentJobs(sessionId)',
    '  const snapshots: Record<string, unknown>[] = []',
    '  for (const [jobId, job] of subagentJobs) {',
    '    const tasks = job.tasks.length > 0 ? job.tasks : [{}]',
    '    tasks.forEach((task, index) => {',
    '      snapshots.push({',
    "        id: tasks.length > 1 ? jobId + ':' + index : jobId,",
    "        state: 'working',",
    '        startedAt: job.startedAt,',
    '        ...task',
    '      })',
    '    })',
    '  }',
    '  return snapshots',
    '}',
    ''
  ]
}
